#!/bin/sh

# Synology package variables
PACKAGE_NAME="starsInstall"
INSTALL_DIR="/var/packages/${PACKAGE_NAME}/target"
PID_FILE="${INSTALL_DIR}/starsInstall.pid"

DAEMON="${INSTALL_DIR}/bin/starsInstall"

# Load common env vars (USER、SYNOPKG_PKGDEST etc.)
source /etc/profile

start_daemon()
{
	# Start your daemon with the desired parameters
		nohup "${DAEMON}" > /dev/null 2>&1 &
    echo $! > "${PID_FILE}"
}

stop_daemon()
{
	# Stop your daemon
  kill "$(cat "${PID_FILE}")"
  rm -f "${PID_FILE}"
}

case "$1" in
	start)
		start_daemon
		exit 0
	;;

	stop)
		stop_daemon
		exit 0
	;;

	status)
		if [ -e "${PID_FILE}" ] && [ -n "$(cat ${PID_FILE})" ]; then
			echo "status: run"
		else
			echo "status: stop"
		fi
		exit 0
		;;
    	killall)
            ;;
    	log)
    		exit 0
    	;;
    esac