#!/bin/sh
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

# Synology package variables
PACKAGE_NAME="stars.synology"
INSTALL_DIR="/var/packages/${PACKAGE_NAME}/target"
PID_FILE="${INSTALL_DIR}/tars.synology.pid"

DAEMON="${INSTALL_DIR}/src/tars.synology"
case $1 in
	start)
		### Start this package.
		start-stop-daemon -b -o -u "${USER}" -S -p "${PID_FILE}" -x "${DAEMON}"
		exit 0
	;;
	stop)
		### Stop this package.
		start-stop-daemon -o -u "${USER}" -K -q -p "${PID_FILE}"
		exit 0
	;;
	status)
		if [ -e "${PID_FILE}" ] && [ -n "$(cat ${PID_FILE})" ]; then
    		echo "status: run"
    else
    		echo "status: stop"
    fi
    exit 0
	;;
	killall)
        ;;
	log)
		exit 0
	;;
esac

